import {join} from 'path'

const sass_dir = join('app', 'stylesheets')
const public_dir = 'public'
const tmp_dir = 'tmp'

export default {
  public_dir,
  sass_dir,
  all_sass_bundles:                  join(sass_dir, '{,plugins/*/}**/[^_]*.s[ac]ss'),
  all_sass_files:                    join(sass_dir, '{,plugins/*/}**/*.s[ac]ss'),
  brandable_variables_json:          join(sass_dir, 'brandable_variables.json'),
  brandable_variables_defaults_scss: join(tmp_dir, '_brandable_variables_defaults_autogenerated.scss'),
  sass_bundles_with_deps:            join(tmp_dir, 'sass-bundles-with-deps.json'),
  sass_file_checksums:               join(tmp_dir, 'sass-file-checksums.json'),
  output_dir:                        join(public_dir, 'stylesheets_compiled'),
  browsers_yml:                      join('config', 'browsers.yml')
}
