const debug = require('debug')('brandable_css')
import {writeFileAsync, readJsonAsync} from 'fs-extra-promise'
import CONFIG from './config'

export default async function writeDefaultBrandableVariablesScss () {
  debug('writing', CONFIG.paths.brandable_variables_defaults_scss)
  let fileContents = '// THIS FILE IS AUTOGENERATED by `brandable_css`. Make changes to: ' + CONFIG.paths.brandable_variables_json
  let variableGrous = await readJsonAsync(CONFIG.paths.brandable_variables_json)
  variableGrous.forEach((variableGroup) => {
    variableGroup.variables.forEach((variable) => {
      let value = variable.default
      if (variable.type === 'image') value = `url("${value}")`
      fileContents += `\n$${variable.variable_name}: ${value} !default;`
    })
  })
  return await writeFileAsync(CONFIG.paths.brandable_variables_defaults_scss, fileContents)
}
